global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'database-monitor'

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s
    metrics_path: /metrics
    params:
      collect[]:
        - 'pg_stat_database'
        - 'pg_stat_user_tables'
        - 'pg_stat_activity'
        - 'pg_locks'
        - 'pg_stat_statements'

  - job_name: 'redshift-exporter'
    static_configs:
      - targets: ['redshift-exporter:9187']
    scrape_interval: 30s
    metrics_path: /metrics
    params:
      collect[]:
        - 'pg_stat_database'
        - 'pg_stat_user_tables'
        - 'pg_stat_activity'
        - 'pg_locks'
        - 'pg_stat_statements'

  - job_name: 'victoria-metrics'
    static_configs:
      - targets: ['victoria-metrics:8428']
    scrape_interval: 30s

remote_write:
  - url: http://victoria-metrics:8428/api/v1/write
    queue_config:
      max_samples_per_send: 10000
      capacity: 20000
      max_shards: 30