apiVersion: 1

datasources:
  - name: VictoriaMetrics
    type: prometheus
    access: proxy
    url: http://victoria-metrics:8428
    uid: VictoriaMetrics
    isDefault: true
    editable: true
    jsonData:
      httpMethod: GET
      timeInterval: 30s

  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    uid: Prometheus
    isDefault: false
    editable: true
    jsonData:
      httpMethod: GET
      timeInterval: 30s